name: 🚀 Publish

on:
  release:
    types: [created]

jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: 📚 Checkout
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: 📦 Dependencies
        run: pnpm install --frozen-lockfile

      - name: ✨ Lint
        run: pnpm lint

      - name: 🛠️ Build
        run: pnpm build

      - name: 🚀 Deploy
        run: pnpm deploy:horizon.js
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
